
services:
  badgeradmin:
    build: .
    container_name: badgeradmin
    ports:
      - "8080:8080"
    environment:
      - BADGER_ADMIN_USER=admin
      - BADGER_ADMIN_PASS=botfluence
    volumes:
      - /root/eyup_x_reply/data:/app/data
